export const commonItemList = [
    'Almonds',
    'Aluminum Foil',
    'Apples',
    'Apricots',
    'Artichokes',
    'Asparagus',
    'Avocado',
    'Baby Formula',
    'Baby Spinach',
    'Bacon',
    'Bagels',
    'Baking Powder',
    'Baking Soda',
    'Bananas',
    'Barley',
    'Basil',
    'Batteries',
    'Batteries - AA',
    'Batteries - AAA',
    'Beef Mince',
    'Beetroot',
    'Berries',
    'Biscuits',
    'Black Beans',
    'Black Tea',
    'Blackberries',
    'Bleach',
    'Blueberries',
    'Bok Choy',
    'Bottled Water',
    'Brandy',
    'Bread',
    'Bread Crumbs',
    'Broccoli',
    'Brown Rice',
    'Brown Sugar',
    'Brussels Sprouts',
    'Butter',
    'Coke',
    'Coke - No Sugar',
    'Coca Cola',
    'Cabbage',
    'Canned Corn',
    'Canned Tomatoes',
    'Canola Oil',
    'Cantaloupe',
    'Capers',
    'Carrots',
    'Cat Food',
    'Cat Litter',
    'Cauliflower',
    'Cayenne Pepper',
    'Celery',
    'Cereal',
    'Champagne',
    'Cheddar Cheese',
    'Cheese',
    'Cherries',
    'Chicken',
    'Chicken Breast',
    'Chicken Broth',
    'Chicken Thighs',
    'Chicken Mince',
    'Chickpeas',
    'Chili Powder',
    'Chips',
    'Chocolate',
    'Cilantro',
    'Cinnamon',
    'Cloves',
    'Cocoa Powder',
    'Coconut Milk',
    'Coconut Oil',
    'Coffee',
    'Coffee Filters',
    'Condensed Milk',
    'Cookies',
    'Cooking Spray',
    'Corn',
    'Cornflakes',
    'Cornmeal',
    'Coriander',
    'Cottage Cheese',
    'Cotton Swabs',
    'Crackers',
    'Cranberries',
    'Cream',
    'Cream Cheese',
    'Cucumbers',
    'Cumin',
    'Curry Powder',
    'Dates',
    'Deli Meat',
    'Dental Floss',
    'Deodorant',
    'Detergent',
    'Diapers',
    'Dill',
    'Dish Soap',
    'Dog Food',
    'Dried Fruit',
    'Dried Herbs',
    'Dry Shampoo',
    'Duck Tape',
    'Edamame',
    'Eggplant',
    'Eggs',
    'English Muffins',
    'Fabric Softener',
    'Facial Tissues',
    'Fennel',
    'Feta Cheese',
    'Fig Bars',
    'Figs',
    'Fish - Fresh',
    'Fish - Frozen',
    'Fish Sauce',
    'Flax Seeds',
    'Flour',
    'Flour Tortillas',
    'Foaming Hand Soap',
    'French Fries',
    'Fresh Herbs',
    'Fruit Cups',
    'Fruit Snacks',
    'Garbanzo Beans',
    'Garlic',
    'Gelatin',
    'Ginger',
    'Glass Cleaner',
    'Gnocchi',
    'Goji Berries',
    'Granola',
    'Grapefruit',
    'Grapes',
    'Greek Yogurt',
    'Green Beans',
    'Green Onions',
    'Ground Beef',
    'Ground Coffee',
    'Ground Turkey',
    'Gruyere Cheese',
    'Guava',
    'Gatorade',
    'Ham',
    'Hamburger Buns',
    'Herbs',
    'Honey',
    'Honeydew Melon',
    'Horseradish',
    'Hot Chocolate Mix',
    'Hot Dogs',
    'Hot Sauce',
    'Hummus',
    'Ice Cream',
    'Iceberg Lettuce',
    'Iced Tea',
    'Instant Coffee',
    'Instant Noodles',
    'Jam',
    'Jasmine Rice',
    'Jelly Beans',
    'Juice',
    'Kale',
    'Ketchup',
    'Kidney Beans',
    'Kiwi',
    'Lamb',
    'Lamb Chops',
    'Lasagna Noodles',
    'Laundry Pods',
    'Lavender',
    'Lemons',
    'Lentils',
    'Lettuce',
    'Lime',
    'Linguine',
    'Liquid Soap',
    'Lobster',
    'Macadamia Nuts',
    'Mackerel',
    'Mangoes',
    'Maple Syrup',
    'Margarine',
    'Marinara Sauce',
    'Marmalade',
    'Marshmallows',
    'Mascarpone',
    'Matcha Powder',
    'Mayonnaise',
    'Melon',
    'Milk',
    'Mint',
    'Mixed Nuts',
    'Mozzarella Cheese',
    'Muesli',
    'Muffins',
    'Mushrooms',
    'Mustard',
    'Napkins',
    'Nectarines',
    'Non-Dairy Milk',
    'Noodles',
    'Nutmeg',
    'Oatmeal',
    'Oats',
    'Olive Oil',
    'Olives',
    'Onions',
    'Orange Juice',
    'Oranges',
    'Oregano',
    'Pancake Mix',
    'Papaya',
    'Paprika',
    'Parmesan Cheese',
    'Parsley',
    'Pasta',
    'Pasta Sauce',
    'Peaches',
    'Pepsi',
    'Peanut Butter',
    'Peanuts',
    'Pears',
    'Peas',
    'Pecans',
    'Pepper',
    'Peppermint',
    'Peppers',
    'Pickles',
    'Pie Crust',
    'Pineapple',
    'Pinto Beans',
    'Pizza',
    'Plums',
    'Popcorn',
    'Pop - Soft Drink',
    'Pork Chops',
    'Portobello Mushrooms',
    'Potato Chips',
    'Potatoes',
    'Powerade',
    'Pretzels',
    'Provolone Cheese',
    'Pumpkin',
    'Pumpkin Seeds',
    'Quinoa',
    'Raisins',
    'Raspberries',
    'Ravioli',
    'Red Bull',
    'Red Onions',
    'Red Wine',
    'Rice',
    'Rice Cakes',
    'Rice Milk',
    'Ricotta Cheese',
    'Rockmelon',
    'Rosemary',
    'Rye Bread',
    'Saffron',
    'Salad Dressing',
    'Salad Mix',
    'Salami',
    'Salmon',
    'Salt',
    'Sandwich Bread',
    'Sardines',
    'Sausages',
    'Scallops',
    'Sea Salt',
    'Seasoning Mix',
    'Sesame Oil',
    'Sesame Seeds',
    'Shampoo',
    'Shaving Cream',
    'Shrimp',
    'Sliced Cheese',
    'Smoked Salmon',
    'Snack Bars',
    'Soda',
    'Soft Drink',
    'Soy Milk',
    'Soy Sauce',
    'Spaghetti',
    'Spaghetti Squash',
    'Sparkling Water',
    'Spinach',
    'Split Peas',
    'Sponge',
    'Sports Drink',
    'Spring Onions',
    'Squash',
    'Steak',
    'Strawberries',
    'String Cheese',
    'Sugar',
    'Sunflower Seeds',
    'Sushi',
    'Sweet Potatoes',
    'Swiss Cheese',
    'Taco Shells',
    'Tahini',
    'Tangerines',
    'Tea',
    'Thyme',
    'Tilapia',
    'Tofu',
    'Toilet Paper',
    'Tomato Paste',
    'Tomato Sauce',
    'Tomatoes',
    'Toothpaste',
    'Tortilla Chips',
    'Tortillas',
    'Trail Mix',
    'Tuna',
    'Turkey',
    'Turnips',
    'Vanilla Extract',
    'Vegan Burgers',
    'Vegetable Broth',
    'Vegetable Oil',
    'Vinegar',
    'Waffles',
    'Walnuts',
    'Water',
    'Water Bottles',
    'Watermelon',
    'Wheat Bread',
    'Whipping Cream',
    'White Rice',
    'White Wine',
    'Whole Chicken',
    'Whole Wheat Flour',
    'Yogurt',
    'Zucchini'
];